### ISSUE TITLE
Set as wallpaper is not working 

### ISSUE THREAD

**Issue by Droidholic** [PDDStudio/earthview-android#15]
While choosing "set as wallpaper" it says unable to set image as wallpaper

**Comment by PDDStudio** [comment]
@Droidholic which SDK are you running? If at least Android +5.0 it should work.
Are you trying to set an Image as Wallpaper while you're **not** connected to a WLan?

**Comment by Droidholic** [comment]
I'm on Android 6.0.1 and I'm connected to WLan when trying to set the image as Wallpaper

**Comment by PDDStudio** [comment]
@Droidholic strange, it should work without any problems then. Which launcher are you using? and did the preview picture reload itself into better quality before you select 'Set as Wallpaper'?

**Comment by Droidholic** [comment]
I'm using Nova launcher currently even tried with Google now launcher but nothing works and yeah preview picture reloaded into better quality before I select the "set as Wallpaper"

**Comment by PDDStudio** [comment]
@Droidholic that's kinda weird now, your setup equals almost completely to mine! Tested it on 6.0.1 with Nova, 6.0 with Nova and 5.1.1 with Nova, worked perfectly on every version for me.
Does this issue happen to every Wallpaper you select or only to a specific one?

**Comment by Droidholic** [comment]
Same happens with every wallpaper

**Comment by PDDStudio** [comment]
@Droidholic I'll try to fix this issue with an upcoming update.

**Comment by PDDStudio** [comment]
@Droidholic I've published a new Version to the PlayStore, please report back whether setting an Image as Wallpaper is working for you with Version +0.3

**Comment by Droidholic** [comment]
"Set as wallpaper" is working now.. Thank you :)﻿
