### ISSUE TITLE
Favorites not working

### ISSUE THREAD

**Issue by Droidholic** [PDDStudio/earthview-android#16]
While choosing "add to favourite" it says "Wallpaper added to favourites!" But unable view favourites

**Comment by PDDStudio** [comment]
@Droidholic thank you for opening this issue, this is already mentioned in #4 
Actually you can only _save/remove_ favorites, but you can not view them yet.
This should be fixed in the next days, no worries - your current favorites won't get lost then so you can still add as much as you want to.

**Comment by Droidholic** [comment]
Thank you and appreciate it :)
