### ISSUE TITLE
Cache Management

### ISSUE THREAD

**Issue by AlexLionne** [PDDStudio/earthview-android#22]
I don't know If cache is optimized (much images are loaded). Why not adding this as option ? It should reduce cache but user will need to sync again each time

``` java
 Picasso.with(context).load(url).memoryPolicy(MemoryPolicy.NO_CACHE )
                        .networkPolicy(NetworkPolicy.NO_CACHE).into(imageView)
```

**Comment by PDDStudio** [comment]
The EarthViewer App itself is doing the cache management. So if you're implementing the library in your own application you've to handle caching & storing yourself.

**Comment by AlexLionne** [comment]
Okay thx for these informations :+1:
