### ISSUE TITLE
Adding Palette ?

### ISSUE THREAD

**Issue by AlexLionne** [PDDStudio/earthview-android#24]
is it possible to add palette to earthviewWallpaper ? it needs to be generated in background

**Comment by PDDStudio** [comment]
You can do this using Android's Pallette Support Library. If you need help with that part feel free to send me a hangout.

**Comment by AlexLionne** [comment]
I know how to do haha It was a way to provide it into the lib :)

**Comment by PDDStudio** [comment]
@AlexLionne I'm not sure whether I get you correctly. So your issue is fixed now?

**Comment by AlexLionne** [comment]
Its was à way to add 
earthviewWallpaper.getAccent() (get accent color from Wallpaper) it was more à question than an issue.

**Comment by PDDStudio** [comment]
@AlexLionne ah, so you mean you want me to include support for the Support Pallette Library in the earthview-android library?
